window.FluentPWACatalog = [
    {
        id: 'process-manager',
        name: '任务管理器',
        category: 'tools',
        icon: 'Taskmgr.png',
        developer: 'NyouOS',
        rating: 4.8,
        downloads: '预装',
        featured: true,
        appType: 'native',
        isNative: true,
        defaultInstalled: true,
        component: 'ProcessManagerApp',
        titleKey: 'process-manager.title',
        width: 1100,
        height: 720,
        minWidth: 760,
        minHeight: 520,
        themeColor: '#0078d4',
        desc: '查看和管理系统进程与内存使用'
    },
    {
        id: 'bilibili',
        name: '哔哩哔哩',
        category: 'video',
        icon: 'bilibili.png',
        developer: 'Bilibili',
        rating: 4.9,
        downloads: '3亿+',
        featured: true,
        url: 'https://www.bilibili.com/',
        width: 1200,
        height: 800,
        themeColor: '#fb7299',
        desc: '弹幕视频网站'
    },
    {
        id: 'douyin',
        name: '抖音',
        category: 'video',
        icon: 'douyin.png',
        developer: '字节跳动',
        rating: 4.7,
        downloads: '10亿+',
        url: 'https://www.douyin.com/',
        width: 1200,
        height: 800,
        themeColor: '#000000',
        desc: '短视频平台'
    },
    {
        id: 'kuaishou',
        name: '快手',
        category: 'video',
        icon: 'douyuzhibo.png',
        developer: '快手',
        rating: 4.6,
        downloads: '5亿+',
        url: 'https://www.kuaishou.com/',
        width: 1200,
        height: 800,
        themeColor: '#ff6600',
        desc: '短视频社区'
    },
    {
        id: 'youku',
        name: '优酷',
        category: 'video',
        icon: 'youku.png',
        developer: '优酷',
        rating: 4.5,
        downloads: '3亿+',
        url: 'https://www.youku.com/',
        width: 1200,
        height: 800,
        themeColor: '#1f6feb',
        desc: '视频分享平台'
    },
    {
        id: 'tencent-video',
        name: '腾讯视频',
        category: 'video',
        icon: 'tencent_video.png',
        developer: '腾讯',
        rating: 4.6,
        downloads: '3亿+',
        url: 'https://v.qq.com/',
        width: 1200,
        height: 800,
        themeColor: '#0052d9',
        desc: '在线视频'
    },
    {
        id: 'iqiyi',
        name: '爱奇艺',
        category: 'video',
        icon: 'videoeditor.png',
        developer: '爱奇艺',
        rating: 4.5,
        downloads: '3亿+',
        url: 'https://www.iqiyi.com/',
        width: 1200,
        height: 800,
        themeColor: '#00be06',
        desc: '视频播放平台'
    },
    {
        id: 'bilibili-live',
        name: '哔哩哔哩直播',
        category: 'video',
        icon: 'bilibili.png',
        developer: 'Bilibili',
        rating: 4.7,
        downloads: '1亿+',
        url: 'https://live.bilibili.com/',
        width: 1200,
        height: 800,
        themeColor: '#fb7299',
        desc: '直播平台'
    },
    {
        id: 'netease-music',
        name: '网易云音乐',
        category: 'music',
        icon: 'wangyiyun_music.png',
        developer: 'NetEase',
        rating: 4.8,
        downloads: '5亿+',
        featured: true,
        url: 'https://music.163.com/',
        width: 1200,
        height: 800,
        themeColor: '#e60026',
        desc: '音乐流媒体'
    },
    {
        id: 'qq-music',
        name: 'QQ音乐',
        category: 'music',
        icon: 'qqmusic.png',
        developer: '腾讯',
        rating: 4.7,
        downloads: '8亿+',
        url: 'https://y.qq.com/',
        width: 1200,
        height: 800,
        themeColor: '#31c27c',
        desc: '在线音乐'
    },
    {
        id: 'kugou',
        name: '酷狗音乐',
        category: 'music',
        icon: 'km1.png',
        developer: '酷狗',
        rating: 4.5,
        downloads: '5亿+',
        url: 'https://www.kugou.com/',
        width: 1200,
        height: 800,
        themeColor: '#00a2ff',
        desc: '音乐播放器'
    },
    {
        id: 'xiami-music',
        name: '虾米音乐',
        category: 'music',
        icon: 'videoeditor.png',
        developer: '虾米',
        rating: 4.3,
        downloads: '5000万+',
        url: 'https://www.xiami.com/',
        width: 1200,
        height: 800,
        themeColor: '#ff5500',
        desc: '音乐社区'
    },
    {
        id: 'kuwo-music',
        name: '酷我音乐',
        category: 'music',
        icon: 'km1.png',
        developer: '酷我',
        rating: 4.4,
        downloads: '1亿+',
        url: 'https://www.kuwo.cn/',
        width: 1200,
        height: 800,
        themeColor: '#1db6cf',
        desc: '音乐下载'
    },
    {
        id: 'taobao',
        name: '淘宝',
        category: 'shopping',
        icon: 'taobao.png',
        developer: '阿里巴巴',
        rating: 4.8,
        downloads: '10亿+',
        featured: true,
        url: 'https://www.taobao.com/',
        width: 1200,
        height: 800,
        themeColor: '#ff5000',
        desc: '综合购物平台'
    },
    {
        id: 'jd',
        name: '京东',
        category: 'shopping',
        icon: 'jingdong.png',
        developer: '京东',
        rating: 4.7,
        downloads: '5亿+',
        featured: true,
        url: 'https://www.jd.com/',
        width: 1200,
        height: 800,
        themeColor: '#e1251b',
        desc: '电商购物'
    },
    {
        id: 'xianyu',
        name: '闲鱼',
        category: 'shopping',
        icon: 'xianyu.png',
        developer: '阿里巴巴',
        rating: 4.6,
        downloads: '3亿+',
        url: 'https://www.goofish.com/',
        width: 1200,
        height: 800,
        themeColor: '#ff9000',
        desc: '二手交易'
    },
    {
        id: 'pdd',
        name: '拼多多',
        category: 'shopping',
        icon: 'pdd.png',
        developer: '拼多多',
        rating: 4.3,
        downloads: '5亿+',
        url: 'https://mobile.yangkeduo.com/',
        width: 1200,
        height: 800,
        themeColor: '#e02e24',
        desc: '社交电商'
    },
    {
        id: 'meituan',
        name: '美团',
        category: 'shopping',
        icon: 'meituan.png',
        developer: '美团',
        rating: 4.7,
        downloads: '5亿+',
        url: 'https://www.meituan.com/',
        width: 1200,
        height: 800,
        themeColor: '#ffd100',
        desc: '生活服务'
    },
    {
        id: 'eleme',
        name: '饿了么',
        category: 'shopping',
        icon: 'meituan.png',
        developer: '饿了么',
        rating: 4.6,
        downloads: '3亿+',
        url: 'https://www.eleme.cn/',
        width: 1200,
        height: 800,
        themeColor: '#0097ff',
        desc: '外卖订餐'
    },
    {
        id: 'taobaoshangou',
        name: '淘宝闪购',
        category: 'shopping',
        icon: 'taobaoshangou.png',
        developer: '阿里巴巴',
        rating: 4.4,
        downloads: '1亿+',
        url: 'https://shangou.taobao.com/',
        width: 1200,
        height: 800,
        themeColor: '#ff5000',
        desc: '即时零售'
    },
    {
        id: 'dangdang',
        name: '当当网',
        category: 'shopping',
        icon: 'office.png',
        developer: '当当',
        rating: 4.3,
        downloads: '1000万+',
        url: 'https://www.dangdang.com/',
        width: 1200,
        height: 800,
        themeColor: '#e01020',
        desc: '图书电商'
    },
    {
        id: 'weibo',
        name: '微博',
        category: 'social',
        icon: 'WB.png',
        developer: '新浪',
        rating: 4.5,
        downloads: '5亿+',
        featured: true,
        url: 'https://weibo.com/',
        width: 1200,
        height: 800,
        themeColor: '#e6162d',
        desc: '社交媒体'
    },
    {
        id: 'zhihu',
        name: '知乎',
        category: 'social',
        icon: 'book.png',
        developer: '知乎',
        rating: 4.7,
        downloads: '1亿+',
        featured: true,
        url: 'https://www.zhihu.com/',
        width: 1200,
        height: 800,
        themeColor: '#0084ff',
        desc: '知识社区'
    },
    {
        id: 'douban',
        name: '豆瓣',
        category: 'social',
        icon: 'gallery.png',
        developer: '豆瓣',
        rating: 4.6,
        downloads: '5000万+',
        url: 'https://www.douban.com/',
        width: 1200,
        height: 800,
        themeColor: '#2d963d',
        desc: '文艺社区'
    },
    {
        id: 'xiaohongshu',
        name: '小红书',
        category: 'social',
        icon: 'pengpai.png',
        developer: '小红书',
        rating: 4.8,
        downloads: '3亿+',
        url: 'https://www.xiaohongshu.com/',
        width: 1200,
        height: 800,
        themeColor: '#ff2442',
        desc: '生活分享'
    },
    {
        id: 'chatgpt',
        name: 'ChatGPT',
        category: 'ai',
        icon: 'chatgpt.png',
        developer: 'OpenAI',
        rating: 4.9,
        downloads: '1亿+',
        banner: true,
        url: 'https://chatgpt.com/',
        width: 1200,
        height: 800,
        themeColor: '#10a37f',
        desc: 'AI对话助手'
    },
    {
        id: 'deepseek',
        name: '深度求索',
        category: 'ai',
        icon: 'deepseek.png',
        developer: 'DeepSeek',
        rating: 4.8,
        downloads: '5000万+',
        featured: true,
        url: 'https://chat.deepseek.com/',
        width: 1200,
        height: 800,
        themeColor: '#4b7bec',
        desc: 'AI编程助手'
    },
    {
        id: 'qwen',
        name: '通义千问',
        category: 'ai',
        icon: 'qwen.png',
        developer: '阿里巴巴',
        rating: 4.7,
        downloads: '1000万+',
        url: 'https://tongyi.aliyun.com/',
        width: 1200,
        height: 800,
        themeColor: '#ff6a00',
        desc: '阿里云AI'
    },
    {
        id: 'kimi',
        name: 'Kimi AI',
        category: 'ai',
        icon: 'kimi.png',
        developer: '月之暗面',
        rating: 4.8,
        downloads: '1000万+',
        featured: true,
        url: 'https://kimi.moonshot.cn/',
        width: 1200,
        height: 800,
        themeColor: '#ff5f00',
        desc: '长文本AI助手'
    },
    {
        id: 'doubao',
        name: '豆包',
        category: 'ai',
        icon: 'deepseek.png',
        developer: '字节跳动',
        rating: 4.6,
        downloads: '5000万+',
        url: 'https://www.doubao.com/',
        width: 1200,
        height: 800,
        themeColor: '#3b82f6',
        desc: 'AI助手'
    },
    {
        id: 'baidu',
        name: '百度搜索',
        category: 'tools',
        icon: 'baidu.png',
        developer: '百度',
        rating: 4.5,
        downloads: '10亿+',
        featured: true,
        url: 'https://www.baidu.com/',
        width: 1200,
        height: 800,
        themeColor: '#2932e1',
        desc: '搜索引擎'
    },
    {
        id: 'baidu-map',
        name: '百度地图',
        category: 'tools',
        icon: 'baidu_map.png',
        developer: '百度',
        rating: 4.4,
        downloads: '5亿+',
        url: 'https://map.baidu.com/',
        width: 1200,
        height: 800,
        themeColor: '#2932e1',
        desc: '地图导航'
    },
    {
        id: 'amap',
        name: '高德地图',
        category: 'tools',
        icon: 'gaode.png',
        developer: '高德',
        rating: 4.7,
        downloads: '8亿+',
        featured: true,
        url: 'https://www.amap.com/',
        width: 1200,
        height: 800,
        themeColor: '#00b578',
        desc: '地图服务'
    },
    {
        id: 'youdao',
        name: '有道翻译',
        category: 'tools',
        icon: 'youdaofanyi.png',
        developer: '网易',
        rating: 4.6,
        downloads: '1亿+',
        url: 'https://fanyi.youdao.com/',
        width: 1200,
        height: 800,
        themeColor: '#4183f5',
        desc: '在线翻译'
    },
    {
        id: 'baidu-translate',
        name: '百度翻译',
        category: 'tools',
        icon: 'translator.png',
        developer: '百度',
        rating: 4.5,
        downloads: '5000万+',
        url: 'https://fanyi.baidu.com/',
        width: 1200,
        height: 800,
        themeColor: '#2932e1',
        desc: '多语言翻译'
    },
    {
        id: 'baidu-netdisk',
        name: '百度网盘',
        category: 'tools',
        icon: 'baidudisk.png',
        developer: '百度',
        rating: 4.4,
        downloads: '3亿+',
        url: 'https://pan.baidu.com/',
        width: 1200,
        height: 800,
        themeColor: '#2932e1',
        desc: '云存储'
    },
    {
        id: 'wechat',
        name: '微信',
        category: 'tools',
        icon: 'wechat.png',
        developer: '腾讯',
        rating: 4.8,
        downloads: '10亿+',
        banner: true,
        url: 'https://weixin.qq.com/',
        width: 1200,
        height: 800,
        themeColor: '#07c160',
        desc: '即时通讯'
    },
    {
        id: 'dingding',
        name: '钉钉',
        category: 'tools',
        icon: 'dingding.png',
        developer: '阿里巴巴',
        rating: 4.5,
        downloads: '5亿+',
        url: 'https://www.dingtalk.com/',
        width: 1200,
        height: 800,
        themeColor: '#1989fa',
        desc: '企业协作'
    },
    {
        id: 'feishu',
        name: '飞书',
        category: 'tools',
        icon: 'dingding.png',
        developer: '字节跳动',
        rating: 4.6,
        downloads: '1亿+',
        url: 'https://www.feishu.cn/',
        width: 1200,
        height: 800,
        themeColor: '#3370ff',
        desc: '企业办公'
    },
    {
        id: 'teams',
        name: 'Microsoft Teams',
        category: 'tools',
        icon: 'dingding.png',
        developer: '微软',
        rating: 4.4,
        downloads: '5亿+',
        url: 'https://teams.microsoft.com/',
        width: 1200,
        height: 800,
        themeColor: '#4647b7',
        desc: '团队协作'
    },
    {
        id: 'qq',
        name: 'QQ',
        category: 'tools',
        icon: 'qqmusic.png',
        developer: '腾讯',
        rating: 4.5,
        downloads: '10亿+',
        url: 'https://im.qq.com/',
        width: 1200,
        height: 800,
        themeColor: '#12b7f5',
        desc: '即时通讯'
    },
    {
        id: 'wangyiyan',
        name: '网易易言',
        category: 'tools',
        icon: 'WB.png',
        developer: '网易',
        rating: 4.3,
        downloads: '100万+',
        url: 'https://yiyan.163.com/',
        width: 1200,
        height: 800,
        themeColor: '#c62828',
        desc: '语音社交'
    },
    {
        id: 'office',
        name: 'Office Online',
        category: 'office',
        icon: 'office.png',
        developer: '微软',
        rating: 4.6,
        downloads: '1亿+',
        url: 'https://www.office.com/',
        width: 1200,
        height: 800,
        themeColor: '#d83b01',
        desc: '办公套件'
    },
    {
        id: 'canva',
        name: 'Canva',
        category: 'office',
        icon: 'canva.png',
        developer: 'Canva',
        rating: 4.8,
        downloads: '1亿+',
        featured: true,
        url: 'https://www.canva.com/',
        width: 1200,
        height: 800,
        themeColor: '#00c4cc',
        desc: '设计工具'
    },
    {
        id: 'shimo',
        name: '石墨文档',
        category: 'office',
        icon: 'shimo_office.png',
        developer: '石墨',
        rating: 4.7,
        downloads: '500万+',
        url: 'https://shimo.im/',
        width: 1200,
        height: 800,
        themeColor: '#333333',
        desc: '协作文档'
    },
    {
        id: 'ticktick',
        name: '滴答清单',
        category: 'office',
        icon: 'didaqingdan.png',
        developer: 'TickTick',
        rating: 4.7,
        downloads: '1000万+',
        featured: true,
        url: 'https://www.dida365.com/',
        width: 1200,
        height: 800,
        themeColor: '#f72d2d',
        desc: '任务管理'
    },
    {
        id: 'notional',
        name: 'Notion',
        category: 'office',
        icon: 'notes.png',
        developer: 'Notion',
        rating: 4.8,
        downloads: '1000万+',
        url: 'https://www.notion.so/',
        width: 1200,
        height: 800,
        themeColor: '#000000',
        desc: '笔记协作'
    },
    {
        id: 'evernote',
        name: '印象笔记',
        category: 'office',
        icon: 'notes.png',
        developer: 'Evernote',
        rating: 4.5,
        downloads: '5000万+',
        url: 'https://www.evernote.com/',
        width: 1200,
        height: 800,
        themeColor: '#00a82d',
        desc: '笔记工具'
    },
    {
        id: 'wps',
        name: 'WPS Office',
        category: 'office',
        icon: 'office.png',
        developer: '金山',
        rating: 4.6,
        downloads: '5亿+',
        url: 'https://www.kdocs.cn/',
        width: 1200,
        height: 800,
        themeColor: '#c62828',
        desc: '办公软件'
    },
    {
        id: 'alipay',
        name: '支付宝',
        category: 'lifestyle',
        icon: 'alipay.png',
        developer: '蚂蚁集团',
        rating: 4.8,
        downloads: '10亿+',
        banner: true,
        url: 'https://www.alipay.com/',
        width: 1200,
        height: 800,
        themeColor: '#1677ff',
        desc: '在线支付'
    },
    {
        id: 'didi',
        name: '滴滴出行',
        category: 'lifestyle',
        icon: 'didi.png',
        developer: '滴滴',
        rating: 4.5,
        downloads: '5亿+',
        url: 'https://www.didi.com/',
        width: 1200,
        height: 800,
        themeColor: '#ff8a00',
        desc: '出行打车'
    },
    {
        id: 'meituan-waimai',
        name: '美团外卖',
        category: 'lifestyle',
        icon: 'meituan.png',
        developer: '美团',
        rating: 4.6,
        downloads: '5亿+',
        url: 'https://waimai.meituan.com/',
        width: 1200,
        height: 800,
        themeColor: '#ffd100',
        desc: '外卖服务'
    },
    {
        id: 'eleme-waimai',
        name: '饿了么外卖',
        category: 'lifestyle',
        icon: 'meituan.png',
        developer: '饿了么',
        rating: 4.6,
        downloads: '3亿+',
        url: 'https://www.eleme.cn/',
        width: 1200,
        height: 800,
        themeColor: '#0097ff',
        desc: '在线订餐'
    },
    {
        id: 'trip',
        name: '携程',
        category: 'lifestyle',
        icon: 'didi.png',
        developer: '携程',
        rating: 4.6,
        downloads: '5亿+',
        url: 'https://www.ctrip.com/',
        width: 1200,
        height: 800,
        themeColor: '#1fa4cc',
        desc: '旅行预订'
    },
    {
        id: 'fliggy',
        name: '飞猪',
        category: 'lifestyle',
        icon: 'didi.png',
        developer: '阿里巴巴',
        rating: 4.5,
        downloads: '1亿+',
        url: 'https://www.fliggy.com/',
        width: 1200,
        height: 800,
        themeColor: '#ff6a00',
        desc: '旅行平台'
    },
    {
        id: 'dianping',
        name: '大众点评',
        category: 'lifestyle',
        icon: 'meituan.png',
        developer: '大众点评',
        rating: 4.5,
        downloads: '1亿+',
        url: 'https://www.dianping.com/',
        width: 1200,
        height: 800,
        themeColor: '#009966',
        desc: '生活消费'
    },
    {
        id: 'chinadaily',
        name: '中国日报',
        category: 'news',
        icon: 'chinadaily.png',
        developer: 'China Daily',
        rating: 4.4,
        downloads: '1000万+',
        url: 'https://www.chinadaily.com.cn/',
        width: 1200,
        height: 800,
        themeColor: '#c62828',
        desc: '新闻资讯'
    },
    {
        id: 'ithome',
        name: 'IT之家',
        category: 'news',
        icon: 'itzhijia.png',
        developer: 'IT之家',
        rating: 4.6,
        downloads: '5000万+',
        featured: true,
        url: 'https://www.ithome.com/',
        width: 1200,
        height: 800,
        themeColor: '#1976d2',
        desc: '科技新闻'
    },
    {
        id: 'thepaper',
        name: '澎湃新闻',
        category: 'news',
        icon: 'chinadaily.png',
        developer: '澎湃',
        rating: 4.5,
        downloads: '3000万+',
        url: 'https://www.thepaper.cn/',
        width: 1200,
        height: 800,
        themeColor: '#ff4b4b',
        desc: '时事新闻'
    },
    {
        id: '36kr',
        name: '36氪',
        category: 'news',
        icon: 'itzhijia.png',
        developer: '36氪',
        rating: 4.5,
        downloads: '1000万+',
        url: 'https://36kr.com/',
        width: 1200,
        height: 800,
        themeColor: '#0080ff',
        desc: '科技创投'
    },
    {
        id: 'snake',
        name: '贪吃蛇',
        category: 'games',
        icon: 'snake.png',
        developer: 'NyouOS',
        rating: 4.5,
        downloads: '内置',
        url: '',
        width: 1200,
        height: 800,
        themeColor: '#22c55e',
        desc: '经典贪吃蛇'
    },
    {
        id: 'puke',
        name: '扑克',
        category: 'games',
        icon: 'puke.png',
        developer: 'NyouOS',
        rating: 4.4,
        downloads: '内置',
        url: '',
        width: 1200,
        height: 800,
        themeColor: '#eab308',
        desc: '纸牌游戏'
    },
    {
        id: 'github',
        name: 'GitHub',
        category: 'developer',
        icon: 'go.png',
        developer: 'GitHub',
        rating: 4.9,
        downloads: '1亿+',
        banner: true,
        url: 'https://github.com/',
        width: 1200,
        height: 800,
        themeColor: '#181717',
        desc: '代码托管'
    },
    {
        id: 'stackoverflow',
        name: 'Stack Overflow',
        category: 'developer',
        icon: 'go.png',
        developer: 'Stack Exchange',
        rating: 4.8,
        downloads: '5000万+',
        url: 'https://stackoverflow.com/',
        width: 1200,
        height: 800,
        themeColor: '#f48024',
        desc: '编程问答'
    },
    {
        id: 'juejin',
        name: '掘金',
        category: 'developer',
        icon: 'go.png',
        developer: '稀土',
        rating: 4.7,
        downloads: '1000万+',
        url: 'https://juejin.cn/',
        width: 1200,
        height: 800,
        themeColor: '#1e88e5',
        desc: '技术社区'
    },
    {
        id: 'csdn',
        name: 'CSDN',
        category: 'developer',
        icon: 'go.png',
        developer: 'CSDN',
        rating: 4.5,
        downloads: '5000万+',
        url: 'https://www.csdn.net/',
        width: 1200,
        height: 800,
        themeColor: '#fc7a00',
        desc: 'IT技术博客'
    },
    {
        id: 'coursera',
        name: 'Coursera',
        category: 'education',
        icon: 'go.png',
        developer: 'Coursera',
        rating: 4.6,
        downloads: '1000万+',
        url: 'https://www.coursera.org/',
        width: 1200,
        height: 800,
        themeColor: '#0056d2',
        desc: '在线学习'
    },
    {
        id: 'zhihu-edu',
        name: '知乎学堂',
        category: 'education',
        icon: 'book.png',
        developer: '知乎',
        rating: 4.5,
        downloads: '500万+',
        url: 'https://www.zhihu.com/',
        width: 1200,
        height: 800,
        themeColor: '#0084ff',
        desc: '知识学习'
    },
    {
        id: 'weread',
        name: '微信读书',
        category: 'education',
        icon: 'reading.png',
        developer: '腾讯',
        rating: 4.7,
        downloads: '1亿+',
        url: 'https://weread.qq.com/',
        width: 1200,
        height: 800,
        themeColor: '#07c160',
        desc: '在线阅读'
    },
    {
        id: 'zhongtai',
        name: '众泰证券',
        category: 'finance',
        icon: 'alipay.png',
        developer: '众泰',
        rating: 4.3,
        downloads: '100万+',
        url: 'https://www.ztsec.com/',
        width: 1200,
        height: 800,
        themeColor: '#c62828',
        desc: '在线炒股'
    }
];